#- name: yum repository
#  yum_repository:
#    name: "{{ item.name }}"
#    baseurl: "{{ item.baseurl }}" 
#    description: "{{ item.name }}"
#    file: "{{ item.file }}"
#  with_items: "{{ repo_centos }}"

- name: yum.conf
  lineinfile:
    dest: "/etc/yum.conf"
    line: "proxy=http://{{ host_ip }}:3128"

- name: repository files
  replace:
    dest: "/etc/yum.repos.d/{{ item.file }}.repo"
    regexp: "^mirrorlist"
    replace: "#mirrorlist"
  with_items: "{{ repo_centos }}"

- name: repository baseurl
  lineinfile:
    dest: "/etc/yum.repos.d/{{ item.file }}.repo"
    insertafter: "^[{{ item.name }}]"
    insertbefore: "^#baseurl"
    line: "baseurl={{ item.baseurl }}"
  with_items: "{{ repo_centos }}"

- name: yum install epel-release centos-release-scl
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - centos-release-scl

- name: repository files
  replace:
    dest: "/etc/yum.repos.d/{{ item.file }}.repo"
    regexp: "^mirrorlist"
    replace: "#mirrorlist"
  with_items: "{{ repo_centos_epel }}"

- name: repository baseurl
  lineinfile:
    dest: "/etc/yum.repos.d/{{ item.file }}.repo"
    insertafter: "^[{{ item.name }}]"
    insertbefore: "^#baseurl"
    line: "baseurl={{ item.baseurl }}"
  with_items: "{{ repo_centos_epel }}"

#- name: docker tag
#  shell: docker tag {{ item.base_os_name }}:{{ item.base_os_tag }} {{ image_name }}:latest
#    name: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
#  with_items: "{{ images }}"

#- name: Start container, connect to network
#  docker_container:
#    name: "{{ item.image_name }}"
#    image: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
#    networks:
#      - name: "{{ network_name }}"
#        ipv4_address: "{{ item.ip }}"
#    command: ["sleep", "infinity"]
#  with_items: "{{ images }}"

#- name: yum install openssh-server (via proxy)
#  shell: "docker exec {{ item.image_name }} /bin/bash -c 'export http_proxy={{ proxy_server }} && yum install openssh-server -y'"
#  with_items: "{{ images }}"
#  when: use_proxy == "y"

#- name: yum install openssh-server
#  shell: "docker exec {{ item.image_name }} yum install openssh-server -y"
#  with_items: "{{ images }}"
#  when: use_proxy == "n"

#- name: sshd-keygen (centos7)
#  shell: "docker exec {{ item.image_name }} /usr/sbin/sshd-keygen"
#  with_items: "{{ images }}"
#  when: item.image_name == "centos7"

#- name: ssh-keygen (centos7)
#  shell: "docker exec {{ item.image_name }} ssh-keygen"
#  with_items: "{{ images }}"

#- name: mkdir .ssh
#  shell: "docker exec {{ item.image_name }} mkdir ~/.ssh"
#  with_items: "{{ images }}"

#- name: copy ssh-key
#  shell: "docker cp ~/.ssh/id_rsa.pub {{ item.image_name }}:/root/.ssh/"
#  with_items: "{{ images }}"

