- name: yum install docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - python2-pip

- name: set proxy to docker
  lineinfile:
    path: /lib/systemd/system/docker.service
    insertbefore: ".*ExecStart.*"
    line: "Environment=\"http_proxy=http://127.0.0.1:3128\""

- name: systemd demon reload
  shell: systemctl daemon-reload

- name: restart docker
  service:
    name: docker
    state: restarted 
    enabled: yes

- name: create directory for python modules
  file:
    path: "{{ pydir }}" 
    state: directory

- name: install docker-ps(python module) 
  pip:
    name: docker-ps
    extra_args: "--prefix {{ pydir }}"
    state: latest
#  environment:
#    https_proxy: "http://127.0.0.1:3128"
