- name: yum install docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - python2-pip

- name: set proxy to docker
  lineinfile:
    path: /lib/systemd/system/docker.service
    insertbefore: ".*ExecStart.*"
    line: "Environment=\"http_proxy={{ proxy_server }}\""
  when: use_proxy == "y"

- name: unset proxy to docker
  lineinfile:
    path: /lib/systemd/system/docker.service
    state: absent
    regexp: "Environment=\'http_proxy=.*"
  when: use_proxy == "n"

- name: set no_proxy to docker
  lineinfile:
    path: /lib/systemd/system/docker.service
    insertbefore: ".*ExecStart.*"
    line: "Environment=\"no_proxy={{ no_proxy }}\""
  when: use_no_proxy == "y"

- name: unset no_proxy to docker
  lineinfile:
    path: /lib/systemd/system/docker.service
    state: absent
    regexp: "Environment=\'no_proxy=.*"
  when: use_no_proxy == "n"

- name: systemd demon reload
  shell: systemctl daemon-reload

- name: restart docker
  service:
    name: docker
    state: restarted 
    enabled: yes

- name: create directory for python modules
  file:
    path: "{{ pydir }}" 
    state: directory

- name: install docker-ps(python module) via proxy 
  pip:
    name: docker-ps
    extra_args: "--prefix {{ pydir }}"
    state: latest
  when: use_proxy == "y"
  environment:
    https_proxy: "{{ proxy_server }}"

- name: install docker-ps(python module)
  pip:
    name: docker-ps
    extra_args: "--prefix {{ pydir }}"
    state: latest
  when: use_proxy == "n"
