- name: Setting environment variables
  blockinfile:
    dest: "/etc/profile.d/ansible_python.sh"
    create: yes
    block: |
      PATH={{ pydir }}/bin:$PATH
      PYTHONPATH={{ pypath }}:$PYTHONPATH
      export PYTHONPATH
