- name: Setting environment variables
  blockinfile:
    dest: "/etc/profile.d/ansible_python.sh"
    create: yes
    block: |
      http_proxy=http://127.0.0.1:3128
      export http_proxy
      https_proxy=http://127.0.0.1:3128
      export https_proxy
      PATH={{ pydir }}/bin:$PATH
      PYTHONPATH={{ pypath }}:$PYTHONPATH
      export PYTHONPATH
