- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

  tasks:
  - name: docker pull os_image
    docker_image:
      name: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
    with_items: "{{ images }}"

  - name: Create a os container
    docker_container:
      name: "{{ item.image_name }}"
      image: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
      command: ["sleep", "infinity"]
    with_items: "{{ images }}"

- hosts: centos
#  become: yes
  connection: docker
  gather_facts: no

  vars_files:
    - "vars/config.yml"

  tasks:
  - name: edit yum.repos.d(mirrorlist)
    replace:
      path: '/etc/yum.repos.d/CentOS-Base.repo'
      regexp: '^(mirrorlist=http://mirrorlist.centos.org.*)$'
      replace: '#\1'

  - name: edit yum.repos.d(Base)
    replace:
      path: '/etc/yum.repos.d/CentOS-Base.repo'
      regexp: '^#(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

  #- name: Setting environment variables(proxy)
  #  blockinfile:
  #    dest: "/etc/profile.d/proxy.sh"
  #    create: yes
  #    block: |
  #      http_proxy=http://{{ gateway }}:3128
  #      export http_proxy
  #      https_proxy=http://{{ gateway }}:3128
  #      export https_proxy

  #- name: set proxy to yum
  #  lineinfile:
  #    path: /etc/yum.conf
  #    line: "proxy=http://{{ gateway }}:3128"

  - name: yum install centos-release-scl
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - centos-release-scl
    environment:
      https_proxy: "http://{{ local_proxy }}"
      http_proxy: "http://{{ local_proxy }}"
      
  - name: edit yum.repos.d(centos-sclo-rh)
    replace:
      path: '/etc/yum.repos.d/CentOS-SCLo-scl-rh.repo'
      regexp: '^(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

  - name: edit yum.repos.d(centos-sclo)
    replace:
      path: '/etc/yum.repos.d/CentOS-SCLo-scl.repo'
      regexp: '^(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

  - name: yum update
    yum:
      name: "*"
      state: latest
    environment:
      https_proxy: "http://{{ local_proxy }}"
      http_proxy: "http://{{ local_proxy }}"

- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

  tasks:
  - name: Stop base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: stopped
    with_items: "{{ images }}"

  - name: absent base_os image
    docker_image:
      name: "{{ item.image_name }}:{{ item.image_tag }}"
      state: absent
    with_items: "{{ images }}"

  - name: docker commit
    shell: docker commit "{{ item.image_name }}" "{{ item.image_name }}:{{ item.image_tag }}"
    with_items: "{{ images }}"

  - name: absent base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: absent
    with_items: "{{ images }}"

