# 概要
#  OpenAduITのイメージ作成
# 説明
#  設定ファイル(vars/config.yml)に記載されている、OpenAduITのイメージを作成する。
#  CentOSC6で作成する。CentOS7での構築手順は未検証
# 実行コマンド
#  ansible-playbook 002003_openaudit_image.yml -i hosts -l localhost,centos6 -vvv

- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

# proxyを使用しない環境ではコメントアウト
#  environment:
#    https_proxy: "http://{{ local_proxy }}"
#    http_proxy: "http://{{ local_proxy }}"

  tasks:

# OSイメージからコンテナを起動
  - name: Create a os container
    docker_container:
      name: "{{ item.image_name }}"
      image: "{{ item.image_name }}:{{ item.image_tag }}"
      command: ["sleep", "infinity"]
      networks:
        - name: "{{ network_name }}"
          ipv4_address: "{{ item.ip }}"
      purge_networks: yes
    with_items: "{{ images }}"

- hosts: centos
  gather_facts: no

  vars_files:
    - "vars/config.yml"

# proxyを使用しない環境ではコメントアウト
#  environment:
#    https_proxy: "http://{{ local_proxy }}"
#    http_proxy: "http://{{ local_proxy }}"

  tasks:

# 必要なパッケージのインストール
  - name: yum install
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - php
      - php-cli
      - php-mysql
      - php-ldap
      - php-mbstring
      - php-mcrypt
      - php-process
      - php-snmp
      - php-xml
      - nmap
      - zip
      - wget
      - sshpass
      - screen
      - samba-client
      - perl-Time-modules
      - ipmitool
      - perl-core
      - mysql
      - mysql-server
      - logrotate
      - python-pip
      - MySQL-python 
    when: inventory_hostname == 'centos6'

# 必要なパッケージのインストール(centos7)
  - name: yum install
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - httpd
      - php
      - php-cli
      - php-mysql
      - php-ldap
      - php-mbstring
      - php-mcrypt
      - php-process
      - php-snmp
      - php-xml
      - nmap
      - zip
      - wget
      - sshpass
      - screen
      - samba-client
      - perl-Time-modules
      - ipmitool
      - perl-core
      - mariadb-server
      - mariadb
      - logrotate
      - python-pip
      - MySQL-python
      - perl-Time-modules
    when: inventory_hostname == 'centos7'

# OpenAudITの対話式インストーラに対応するため、ansibleのモジュールで必要とするパッケージのインストール。
  - name: pip install pexpect
    pip:
      name: "{{ item }}"
      state: latest
    with_items:
      - pexpect

# Apacheのデフォルトページの設定無効化の確認
  - name: /etc/httpd/conf.d/welcome.conf check
    stat: path=/etc/httpd/conf.d/welcome.conf.org
    register: foo_stat

# 無効化していない場合、ファイル名変更で無効化
  - name: Move welcome.conf to welcome.conf.org
    command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.org
    when: not foo_stat.stat.exists

# Apacheのデフォルトの設定ファイルのバックアップ確認
  - name: /etc/httpd/conf/httpd.conf check
    stat: path=/etc/httpd/conf/httpd.conf.org
    register: foo_stat

# バックアップがない場合はバックアップ（移動）
  - name: Move httpd.conf to httpd.conf.org
    command: mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.org
    when: not foo_stat.stat.exists

# 起動シェル、Apacheの設定ファイル、Apacheのセキュリティ用の設定ファイルのコピー
  - name: Copies files to remote locations
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: u=rwx,g=r,o=r
    with_items:
      - { src: "files/openaudit/openaudit_6.sh", dest: "/usr/local/bin/openaudit.sh" }
      - { src: "files/openaudit/httpd.conf", dest: "/etc/httpd/conf/httpd.conf" }
      - { src: "files/openaudit/security.conf", dest: "/etc/httpd/conf.d/security.conf" }
    when: inventory_hostname == 'centos6'

# 起動シェル、Apacheの設定ファイル、Apacheのセキュリティ用の設定ファイルのコピー（CentOS7用）
  - name: Copies files to remote locations
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: u=rwx,g=r,o=r
    with_items:
      - { src: "files/openaudit/openaudit_7.sh", dest: "/usr/local/bin/openaudit.sh" }
      - { src: "files/openaudit/httpd.conf", dest: "/etc/httpd/conf/httpd.conf" }
      - { src: "files/openaudit/security.conf", dest: "/etc/httpd/conf.d/security.conf" }
    when: inventory_hostname == 'centos7'

# MySQLの起動、自動起動設定
  - name: start mysqld
    service:
      name: mysqld
      state: started
    when: inventory_hostname == 'centos6'

# MySQL(MariaDB)の初期設定 (CentOS7)
  - name: init mysql
    shell: /usr/bin/mysql_install_db
    when: inventory_hostname == 'centos7'

# MySQL(MariaDB)で使用するフォルダの権限変更 (CentOS7)
  - name: Change file permissions (/var/lib/mysql)
    shell: chown mysql:mysql /var/lib/mysql -R
    when: inventory_hostname == 'centos7'

# MySQL(MariaDB)の起動 (CentOS7)
  - name: start mysqld
    shell: /usr/bin/mysqld_safe --datadir='/var/lib/mysql' &
    when: inventory_hostname == 'centos7'

# OpenAudITのデータを外部から参照するためのユーザ作成
  - name: mysql user
    shell: echo "grant select on openaudit.* to 'openauditview'@'%' identified by '{{ openaudit_mysql_pass }}' with grant option" | mysql 
 
# MySQLのrootユーザのパスワード設定
  - mysql_user:
      name: root
      password: "{{ openaudit_mysql_pass }}"
    ignore_errors: True 

# デフォルトで動作しているが、もし日本語で化けることがあったら、
# 以下のように、DBの文字コードの設定が必要かも。
#  - name: edit /etc/my.cnf
#    lineinfile:
#      path: /etc/my.cnf
#      line: "{{ item }}"
#    with_items:
#      - "[client]"
#      - "default-character-set=utf8"

#  - name: edit /etc/my.cnf
#    replace:
#      path: /etc/my.cnf
#      regexp: "({{ item }})"
#      replace: '\1\ndefault-character-set=utf8'
#    with_items:
#      - '\[mysqld\]'
#      - '\[mysqld_safe\]'

#  - name: restart mysqld
#    service:
#      name: mysqld
#      state: restarted
#    when: inventory_hostname == 'centos6'

#  - name: stop mysqld
#    shell: /bin/kill -TERM `cat /var/run/mariadb/mariadb.pid`
#    when: inventory_hostname == 'centos7'

#  - name: start mysqld
#    shell: /usr/bin/mysqld_safe --datadir='/var/lib/mysql' &
#    when: inventory_hostname == 'centos7'

# OpenAudIT推奨値、セキュリティ(expose_php)、エラーログ(error_log)の設定ために、一旦コメントアウト
  - name: edit php.ini(comment out)
    replace:
      path: '/etc/php.ini'
      regexp: "^{{ item }}"
      replace: ";{{ item }}"
    with_items:
      - 'memory_limit'
      - 'max_execution_time'
      - 'max_input_time'
      - 'error_reporting'
      - 'display_errors'
      - 'upload_max_filesize'
      - 'date.timezone'
      - 'expose_php'
      - 'error_log'

# OpenAudIT推奨値、セキュリティ(expose_php)、エラーログ(error_log)の設定
  - name: edit php.ini
    lineinfile:
      path: '/etc/php.ini'
      line: "{{ item.value }}"
      insertafter: "^;{{ item.name }}"
    with_items:
      - { name: 'memory_limit'       , value: 'memory_limit = 512M'        }
      - { name: 'max_execution_time' , value: 'max_execution_time = 300'   }
      - { name: 'max_input_time'     , value: 'max_input_time = 600'       }
      - { name: 'error_reporting'    , value: 'error_reporting = E_ALL'    }
      - { name: 'display_errors'     , value: 'display_errors = On'        }
      - { name: 'upload_max_filesize', value: 'upload_max_filesize = 10M'  }
      - { name: 'date.timezone'      , value: 'date.timezone = Asia/Tokyo' }
      - { name: 'expose_php'         , value: 'expose_php = Off'           }
      - { name: 'error_log'          , value: 'error_log = /var/log/php/php_error.log' }

# PHPのエラーログの出力先作成
  - name: create directory for php
    file:
      path: "{{ item }}"
      state: directory
      owner: apache
      group: apache
    with_items:
      - /var/log/php

# OpenAudITのインストーラのダウンロード
  - name: download openaudit_install_file
    get_url:
      url: http://dl-openaudit.opmantek.com/{{ openaudit_install_file }}
      dest: /root/{{ openaudit_install_file }}

# OpenAudITのインストーラに実行権限の付与
  - name: chmod +x openaudit_install_file
    file:
      path: "/root/{{ openaudit_install_file }}"
      mode: "a+x"
      state: file

# OpenAudITのインストーラの実行（対話式）。デフォルト＋MySQLのパスワードを設定。
  - name: openaudit install
    expect:
      command: "/root/{{ openaudit_install_file }}"
      responses:
        "Type 'y' or hit <Enter> to accept, any other key for 'no': ": "y"
        "Hit <Enter> when ready to continue: ": ""
        "Enter the MySQL root user's password: ": "{{ openaudit_mysql_pass }}"
      timeout: 600

# DB接続情報の編集
  - name: edit database.php
    replace:
      path: "/usr/local/open-audit/code_igniter/application/config/database.php"
      regexp: "localhost"
      replace: "127.0.0.1"

# DB接続情報の編集
  - name: edit database.php -2
    replace:
      path: "/usr/local/open-audit/code_igniter/application/config/database.php"
      regexp: "openauditpassword"
      replace: "{{ openaudit_mysql_pass }}"

# openauditで作成されたDBユーザのパスワード変更
  - name: change openaudit database password
    mysql_user:
      login_user: root
      login_password: "{{ openaudit_mysql_pass }}"
      name: openaudit
      host: localhost
      password: "{{ openaudit_mysql_pass }}"
      state: present

# OpenAudITの初期データ（MySQL）のバックアップ
  - name: copy mysql datadir
    shell: cp -pr /var/lib/mysql/ /root/

# OpenAudITの初期データ（ログ）のバックアップ
  - name: copy log dir
    shell: cp -pr /var/log/ /root/

- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

# proxyを使用しない環境ではコメントアウト
#  environment:
#    https_proxy: "http://{{ local_proxy }}"
#    http_proxy: "http://{{ local_proxy }}"

  tasks:

# コンテナを停止
  - name: Stop base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: stopped
    with_items: "{{ images }}"

# 不要なイメージがあった場合に削除
  - name: absent base_os image
    docker_image:
      name: "{{ item.image_name }}:{{ item.image_tag }}"
      state: absent
    with_items: "{{ openaudit }}"

# 作成したコンテナからイメージを作成
  - name: docker commit
    shell: docker commit "{{ item.base_os_name }}" "{{ item.image_name }}:{{ item.image_tag }}"
    with_items: "{{ openaudit }}"

# コンテナを削除
  - name: absent base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: absent
    with_items: "{{ images }}"

