# 概要
#  ベースとなるOSのイメージ作成
# 説明
#  設定ファイル(vars/config.yml)に記載されている、OSのイメージを作成する。
# 実行コマンド
#  ansible-playbook 002001_os_image.yml -i hosts -l localhost,centos -vvv

- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

# proxyを使用しない環境ではコメントアウト
#  environment:
#    https_proxy: "http://{{ local_proxy }}"
#    http_proxy: "http://{{ local_proxy }}"

  tasks:

# Docker HubからCentOSの公式イメージを取得
  - name: docker pull os_image
    docker_image:
      name: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
    with_items: "{{ images }}"

# イメージからコンテナを起動
  - name: Create a os container
    docker_container:
      name: "{{ item.image_name }}"
      image: "{{ item.base_os_name }}:{{ item.base_os_tag }}"
      command: ["sleep", "infinity"]
      networks:
        - name: "{{ network_name }}"
          ipv4_address: "{{ item.ip }}"
      purge_networks: yes
    with_items: "{{ images }}"

# 起動したcentosのコンテナに対して変更を行う
- hosts: centos
  gather_facts: no

  vars_files:
    - "vars/config.yml"

# proxyを使用しない環境ではコメントアウト
#  environment:
#    https_proxy: "http://{{ local_proxy }}"
#    http_proxy: "http://{{ local_proxy }}"

  tasks:

# ベースリポジトリサーバを日本(ftp.riken.jp)に固定するため、mirrolistをコメントアウト。
  - name: edit yum.repos.d(base mirrorlist)
    replace:
      path: '/etc/yum.repos.d/CentOS-Base.repo'
      regexp: '^(mirrorlist=http://mirrorlist.centos.org.*)$'
      replace: '#\1'

# ベースリポジトリサーバを日本(ftp.riken.jp)に変更する。
  - name: edit yum.repos.d(base baseurl)
    replace:
      path: '/etc/yum.repos.d/CentOS-Base.repo'
      regexp: '^#(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

# SCLのリポジトリを追加
  - name: yum install centos-release-scl
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - centos-release-scl
      
# SCLのベースリポジトリサーバを日本(ftp.riken.jp)に変更する。
  - name: edit yum.repos.d(centos-sclo-rh)
    replace:
      path: '/etc/yum.repos.d/CentOS-SCLo-scl-rh.repo'
      regexp: '^(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

# SCLのベースリポジトリサーバを日本(ftp.riken.jp)に変更する。
  - name: edit yum.repos.d(centos-sclo)
    replace:
      path: '/etc/yum.repos.d/CentOS-SCLo-scl.repo'
      regexp: '^(baseurl=http://)(mirror.centos.org)(.*)$'
      replace: '\1ftp.riken.jp/Linux\3'

# EPELのリポジトリを追加
  - name: yum install epel-release
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - epel-release

# EPELのベースリポジトリサーバを日本(ftp.riken.jp)に固定するため、mirrolistをコメントアウト。
  - name: edit yum.repos.d(epel mirrorlist)
    replace:
      path: '/etc/yum.repos.d/epel.repo'
      regexp: '^(mirrorlist=https://mirrors.fedoraproject.org.*)$'
      replace: '#\1'

# EPELのベースリポジトリサーバを日本(ftp.riken.jp)に変更する。
  - name: edit yum.repos.d(epel baseurl)
    replace:
      path: '/etc/yum.repos.d/epel.repo'
      regexp: '^#(baseurl=http://)(download.fedoraproject.org/pub/)(.*)$'
      replace: '\1ftp.riken.jp/Linux/fedora/\3'

# マイナーバージョンリリース時のパッケージを最新状態までアップデート
  - name: yum update
    yum:
      name: "*"
      state: latest

- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

  tasks:
# コンテナを停止
  - name: Stop base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: stopped
    with_items: "{{ images }}"

# 不要なイメージがあった場合に削除
  - name: absent base_os image
    docker_image:
      name: "{{ item.image_name }}:{{ item.image_tag }}"
      state: absent
    with_items: "{{ images }}"

# 作成したコンテナからイメージを作成
  - name: docker commit
    shell: docker commit "{{ item.image_name }}" "{{ item.image_name }}:{{ item.image_tag }}"
    with_items: "{{ images }}"

# コンテナを削除
  - name: absent base_os container
    docker_container:
      name: "{{ item.image_name }}"
      state: absent
    with_items: "{{ images }}"

