- hosts: dockerhost
  become: yes

  vars_files:
    - "vars/config.yml"

  tasks:

  - name: Create a yum container
    docker_container:
      name: "{{ item.image_name }}"
      image: "{{ item.image_name }}:{{ item.image_tag }}"
      hostname: "{{ item.image_name }}"
      networks:
        - name: "{{ network_name }}"
          ipv4_address: "{{ item.ip }}"
      volumes:
        - "/opt/dockerpv/{{ item.image_name }}/var/log:/var/log"
        - "/opt/dockerpv/{{ item.image_name }}/var/cache/yum:/var/cache/yum"
        - "/opt/dockerpv/{{ item.image_name }}/var/lib/yum:/var/lib/yum"
        - "/etc/localtime:/etc/localtime:ro"
        - "{{ item.dir }}:{{ item.dir }}"
      command: ["sleep", "infinity"]
      purge_networks: yes
    with_items: "{{ yum_repo }}"
