- hosts: all
#- hosts: localhost
  gather_facts: no
  connection: docker
  become: no
  vars:
    ip: xxx.xxx.xxx.xxx
    local_server:
      - '    zzz "{{ ip }}"'
      - '    yyy "{{ ip }}"'
  tasks:
   - command: ls
#  - name: Setting environment variables to unbound
#    blockinfile:
#      dest: "/tmp/local.conf"
#      create: yes
#      marker: ""
#      block: |
#        {{ item }}
#    with_items:
#        "{{ local_server }}"

#  - name: Setting environment variables to unbound
#    lineinfile:
#      dest: "/tmp/local.conf"
#      create: yes
#      line: "{{ item }}"
#    with_items:
#      - '    xxx "{{ ip }}"'
#      - '    yyy "{{ ip }}"'
