- name: yum install httpd
  yum:
    name: httpd 
    state: latest

- name: start httpd
  service:
    name: httpd
    state: started 
    enabled: yes

- name: allow access from container to host
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: set rule to iptables
  lineinfile:
    dest: "/etc/sysconfig/iptables"
    insertafter: "^:OUTPUT"
#    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT"
    line: "-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT"
