- name: Stop base_os container
  docker_container:
    name: "{{ item.base_os_name }}"
    state: stopped
  with_items: "{{ yum_repo }}"

- name: absent base_os image
  docker_image:
    name: "{{ item.image_name }}:{{ item.image_tag }}" 
    state: absent
  with_items: "{{ yum_repo }}"

- name: docker commit
  shell: docker commit "{{ item.base_os_name }}" "{{ item.image_name }}:{{ item.image_tag }}"
  with_items: "{{ yum_repo }}"

- name: absent base_os container
  docker_container:
    name: "{{ item.base_os_name }}"
    state: absent
  with_items: "{{ yum_repo }}"
