- name: yum install unbound
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unbound
    - NetworkManager-glib

- name: initialize local-zone,forward-zone to unbound 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/unbound/local.d/local-zone.conf
    - /etc/unbound/conf.d/forward-zone.conf

- name: Setting environment variables to unbound(local-zone)
  lineinfile:
    dest: "/etc/unbound/local.d/local-zone.conf"
    create: yes
    line: "{{ item }}"
  with_items:
      "{{ local_server }}"

- name: Setting environment variables to unbound(forward-zone)
  lineinfile:
    dest: "/etc/unbound/conf.d/forward-zone.conf"
    create: yes
    line: "{{ item }}"
  with_items:
      "{{ forward_zone }}"

- name: restart unbound
  service:
    name: unbound
    state: restarted
    enabled: yes

- name: Setting DNS Server to resolve.conf
  nmcli:
    conn_name: "{{ nic_interface }}" 
    type: ethernet
    dns4: "{{ host_ip }}"
    state: present

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes
